version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "monthly"
    target-branch: "master"
    commit-message:
      prefix: "chore"
      include: "scope"
